// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"

lv_obj_t * uic_call;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_calls = NULL;
lv_obj_t * ui_nuse = NULL;
lv_obj_t * ui_PanelS = NULL;
lv_obj_t * ui_LabelHora = NULL;
lv_obj_t * ui_LabelAMPM = NULL;
lv_obj_t * ui_InfoPaciente = NULL;
lv_obj_t * ui_InfoPaciente2 = NULL;
lv_obj_t * ui_namepaciente = NULL;
lv_obj_t * ui_LabelNombre = NULL;
lv_obj_t * ui_ubi1 = NULL;
// event funtions
void ui_event_calls(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_PanelS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_InfoPaciente(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_InfoPaciente2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_namepaciente(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_ubi1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calls = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_calls, 300);
    lv_obj_set_height(ui_calls, 328);
    lv_obj_set_x(ui_calls, 0);
    lv_obj_set_y(ui_calls, -40);
    lv_obj_set_align(ui_calls, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calls, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_calls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_calls, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_calls, lv_color_hex(0x074E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_calls, lv_color_hex(0xC11010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_calls, lv_color_hex(0xC7DCC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_calls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_calls, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nuse = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_nuse, &ui_img_nursev3_png);
    lv_obj_set_width(ui_nuse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nuse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nuse, 0);
    lv_obj_set_y(ui_nuse, -42);
    lv_obj_set_align(ui_nuse, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nuse, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_nuse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_nuse, 200);

    ui_PanelS = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelS, 469);
    lv_obj_set_height(ui_PanelS, 70);
    lv_obj_set_x(ui_PanelS, 1);
    lv_obj_set_y(ui_PanelS, -280);
    lv_obj_set_align(ui_PanelS, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHora = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHora, 140);
    lv_obj_set_height(ui_LabelHora, 31);
    lv_obj_set_x(ui_LabelHora, -156);
    lv_obj_set_y(ui_LabelHora, -285);
    lv_obj_set_align(ui_LabelHora, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHora, "00:00:00");
    lv_obj_set_style_text_font(ui_LabelHora, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAMPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelAMPM, 56);
    lv_obj_set_height(ui_LabelAMPM, 30);
    lv_obj_set_x(ui_LabelAMPM, -64);
    lv_obj_set_y(ui_LabelAMPM, -285);
    lv_obj_set_align(ui_LabelAMPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAMPM, "A/P");
    lv_obj_set_style_text_font(ui_LabelAMPM, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoPaciente = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_InfoPaciente, 469);
    lv_obj_set_height(ui_InfoPaciente, 70);
    lv_obj_set_x(ui_InfoPaciente, 0);
    lv_obj_set_y(ui_InfoPaciente, 204);
    lv_obj_set_align(ui_InfoPaciente, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoPaciente, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InfoPaciente, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InfoPaciente, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoPaciente, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoPaciente2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_InfoPaciente2, 469);
    lv_obj_set_height(ui_InfoPaciente2, 70);
    lv_obj_set_x(ui_InfoPaciente2, 0);
    lv_obj_set_y(ui_InfoPaciente2, 280);
    lv_obj_set_align(ui_InfoPaciente2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoPaciente2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InfoPaciente2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InfoPaciente2, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoPaciente2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namepaciente = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_namepaciente, 454);
    lv_obj_set_height(ui_namepaciente, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_namepaciente, 0);
    lv_obj_set_y(ui_namepaciente, 201);
    lv_obj_set_align(ui_namepaciente, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namepaciente, "");
    lv_obj_set_style_text_align(ui_namepaciente, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namepaciente, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombre = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelNombre, 402);
    lv_obj_set_height(ui_LabelNombre, 30);
    lv_obj_set_x(ui_LabelNombre, 28);
    lv_obj_set_y(ui_LabelNombre, 280);
    lv_obj_set_align(ui_LabelNombre, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombre, "LabelNombre");
    lv_obj_set_style_text_font(ui_LabelNombre, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ubi1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ubi1, &ui_img_ubi_png);
    lv_obj_set_width(ui_ubi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ubi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ubi1, -206);
    lv_obj_set_y(ui_ubi1, 280);
    lv_obj_set_align(ui_ubi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ubi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ubi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ubi1, 180);

    lv_obj_add_event_cb(ui_calls, ui_event_calls, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelS, ui_event_PanelS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InfoPaciente, ui_event_InfoPaciente, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InfoPaciente2, ui_event_InfoPaciente2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_namepaciente, ui_event_namepaciente, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ubi1, ui_event_ubi1, LV_EVENT_ALL, NULL);
    uic_call = ui_calls;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_call = NULL;
    ui_calls = NULL;
    ui_nuse = NULL;
    ui_PanelS = NULL;
    ui_LabelHora = NULL;
    ui_LabelAMPM = NULL;
    ui_InfoPaciente = NULL;
    ui_InfoPaciente2 = NULL;
    ui_namepaciente = NULL;
    ui_LabelNombre = NULL;
    ui_ubi1 = NULL;

}
