// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_PanelS2;
extern lv_obj_t * ui_PanelI2;
extern lv_obj_t * ui_LabelHora2;
extern lv_obj_t * ui_LabelAMPM2;
extern lv_obj_t * ui_LabelNombre2;
extern lv_obj_t * ui_ubi3;
extern lv_obj_t * ui_TabView1Info;
extern lv_obj_t * ui_Labelubicacionsede;
extern void ui_event_PanelIp(lv_event_t * e);
extern lv_obj_t * ui_PanelIp;
extern lv_obj_t * ui_PanelMac;
extern lv_obj_t * ui_Panel2;
extern void ui_event_inicio(lv_event_t * e);
extern lv_obj_t * ui_inicio;
extern lv_obj_t * ui_LabelIp;
extern lv_obj_t * ui_LabelMac;
extern lv_obj_t * ui_LabelInicio;
extern void ui_event_RESET(lv_event_t * e);
extern lv_obj_t * ui_RESET;
extern lv_obj_t * ui_RESET1;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_EspNowConfigButton;
extern lv_obj_t * ui_EspNowConfigPanel;
extern lv_obj_t * ui_EspNowMacInput;
extern lv_obj_t * ui_EspNowChannelDropdown;
extern lv_obj_t * ui_EspNowConfigStatus;
extern lv_obj_t * ui_EspNowKeyboard;
// CUSTOM VARIABLES
extern lv_obj_t * uic_inicio;

void ui_show_espnow_config(const char *gatewayMac, uint8_t channel);
void ui_hide_espnow_config(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

