// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2-esp_now

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_PanelDatos2;
extern lv_obj_t * ui_Labelconfig;
extern lv_obj_t * ui_PanelNombre2;
extern lv_obj_t * ui_Labelmsdebug;
extern void ui_event_inicio3(lv_event_t * e);
extern lv_obj_t * ui_inicio3;
extern lv_obj_t * ui_LabelInicio3;
extern lv_obj_t * ui_Switchtms;
extern lv_obj_t * ui_Panelmsdebug;
extern lv_obj_t * ui_Labelmonitorserial;
extern lv_obj_t * ui_Sliderbrillo;
extern lv_obj_t * ui_Labelmsdebug1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
