// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREEN0_H
#define UI_SCREEN0_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen0
extern void ui_Screen0_screen_init(void);
extern void ui_Screen0_screen_destroy(void);
extern lv_obj_t * ui_Screen0;
extern void ui_event_RESET3(lv_event_t * e);
extern lv_obj_t * ui_RESET3;
extern lv_obj_t * ui_RESET4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

