// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_PanelDatos;
extern lv_obj_t * ui_LabelDatos;
extern lv_obj_t * ui_PanelNombre;
extern lv_obj_t * ui_LabelNombre3;
extern lv_obj_t * ui_LabelNombrePaciente4;
extern lv_obj_t * ui_PanelEdad;
extern lv_obj_t * ui_LabelEdad;
extern lv_obj_t * ui_LabelEdadPaciente4;
extern lv_obj_t * ui_PanelIngesoFecha;
extern lv_obj_t * ui_LabelFechaIngreso;
extern lv_obj_t * ui_LabelIngresoFecha4;
extern lv_obj_t * ui_PanelNotas;
extern lv_obj_t * ui_LabelNotas;
extern lv_obj_t * ui_LabelNotasPaciente4;
extern void ui_event_inicio2(lv_event_t * e);
extern lv_obj_t * ui_inicio2;
extern lv_obj_t * ui_LabelInicio2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

