// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_PanelDatos = NULL;
lv_obj_t * ui_LabelDatos = NULL;
lv_obj_t * ui_PanelNombre = NULL;
lv_obj_t * ui_LabelNombre3 = NULL;
lv_obj_t * ui_LabelNombrePaciente4 = NULL;
lv_obj_t * ui_PanelEdad = NULL;
lv_obj_t * ui_LabelEdad = NULL;
lv_obj_t * ui_LabelEdadPaciente4 = NULL;
lv_obj_t * ui_PanelIngesoFecha = NULL;
lv_obj_t * ui_LabelFechaIngreso = NULL;
lv_obj_t * ui_LabelIngresoFecha4 = NULL;
lv_obj_t * ui_PanelNotas = NULL;
lv_obj_t * ui_LabelNotas = NULL;
lv_obj_t * ui_LabelNotasPaciente4 = NULL;
lv_obj_t * ui_inicio2 = NULL;
lv_obj_t * ui_LabelInicio2 = NULL;
// event funtions
void ui_event_inicio2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelDatos = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelDatos, 469);
    lv_obj_set_height(ui_PanelDatos, 70);
    lv_obj_set_x(ui_PanelDatos, 0);
    lv_obj_set_y(ui_PanelDatos, -280);
    lv_obj_set_align(ui_PanelDatos, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDatos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDatos = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelDatos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDatos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDatos, -4);
    lv_obj_set_y(ui_LabelDatos, -281);
    lv_obj_set_align(ui_LabelDatos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDatos, "Datos del Paciente");
    lv_obj_set_style_text_color(ui_LabelDatos, lv_color_hex(0x46BDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDatos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDatos, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNombre = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelNombre, 469);
    lv_obj_set_height(ui_PanelNombre, 70);
    lv_obj_set_x(ui_PanelNombre, 0);
    lv_obj_set_y(ui_PanelNombre, -172);
    lv_obj_set_align(ui_PanelNombre, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNombre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNombre3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelNombre3, 110);
    lv_obj_set_height(ui_LabelNombre3, 25);
    lv_obj_set_x(ui_LabelNombre3, -177);
    lv_obj_set_y(ui_LabelNombre3, -223);
    lv_obj_set_align(ui_LabelNombre3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombre3, "Nombre:");
    lv_obj_set_style_text_color(ui_LabelNombre3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNombre3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNombre3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombrePaciente4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelNombrePaciente4, 455);
    lv_obj_set_height(ui_LabelNombrePaciente4, 57);
    lv_obj_set_x(ui_LabelNombrePaciente4, 0);
    lv_obj_set_y(ui_LabelNombrePaciente4, -172);
    lv_obj_set_align(ui_LabelNombrePaciente4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombrePaciente4, "Sin datos del paciente");
    lv_obj_set_style_text_font(ui_LabelNombrePaciente4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEdad = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelEdad, 469);
    lv_obj_set_height(ui_PanelEdad, 70);
    lv_obj_set_x(ui_PanelEdad, 0);
    lv_obj_set_y(ui_PanelEdad, -73);
    lv_obj_set_align(ui_PanelEdad, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEdad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelEdad = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelEdad, 85);
    lv_obj_set_height(ui_LabelEdad, 22);
    lv_obj_set_x(ui_LabelEdad, -186);
    lv_obj_set_y(ui_LabelEdad, -124);
    lv_obj_set_align(ui_LabelEdad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEdad, "Edad:");
    lv_obj_set_style_text_color(ui_LabelEdad, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEdad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEdad, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEdadPaciente4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelEdadPaciente4, 455);
    lv_obj_set_height(ui_LabelEdadPaciente4, 57);
    lv_obj_set_x(ui_LabelEdadPaciente4, 0);
    lv_obj_set_y(ui_LabelEdadPaciente4, -75);
    lv_obj_set_align(ui_LabelEdadPaciente4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEdadPaciente4, "");
    lv_obj_set_style_text_font(ui_LabelEdadPaciente4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIngesoFecha = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelIngesoFecha, 469);
    lv_obj_set_height(ui_PanelIngesoFecha, 70);
    lv_obj_set_x(ui_PanelIngesoFecha, 0);
    lv_obj_set_y(ui_PanelIngesoFecha, 31);
    lv_obj_set_align(ui_PanelIngesoFecha, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIngesoFecha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFechaIngreso = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelFechaIngreso, 102);
    lv_obj_set_height(ui_LabelFechaIngreso, 25);
    lv_obj_set_x(ui_LabelFechaIngreso, -179);
    lv_obj_set_y(ui_LabelFechaIngreso, -19);
    lv_obj_set_align(ui_LabelFechaIngreso, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFechaIngreso, "Ingreso:");
    lv_obj_set_style_text_color(ui_LabelFechaIngreso, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFechaIngreso, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFechaIngreso, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIngresoFecha4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelIngresoFecha4, 455);
    lv_obj_set_height(ui_LabelIngresoFecha4, 57);
    lv_obj_set_x(ui_LabelIngresoFecha4, 0);
    lv_obj_set_y(ui_LabelIngresoFecha4, 30);
    lv_obj_set_align(ui_LabelIngresoFecha4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIngresoFecha4, "");
    lv_obj_set_style_text_font(ui_LabelIngresoFecha4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotas = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelNotas, 469);
    lv_obj_set_height(ui_PanelNotas, 98);
    lv_obj_set_x(ui_PanelNotas, 0);
    lv_obj_set_y(ui_PanelNotas, 143);
    lv_obj_set_align(ui_PanelNotas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNotas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNotas = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelNotas, 81);
    lv_obj_set_height(ui_LabelNotas, 28);
    lv_obj_set_x(ui_LabelNotas, -192);
    lv_obj_set_y(ui_LabelNotas, 81);
    lv_obj_set_align(ui_LabelNotas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNotas, "Notas:");
    lv_obj_set_style_text_color(ui_LabelNotas, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNotas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNotas, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotasPaciente4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelNotasPaciente4, 469);
    lv_obj_set_height(ui_LabelNotasPaciente4, 86);
    lv_obj_set_x(ui_LabelNotasPaciente4, 0);
    lv_obj_set_y(ui_LabelNotasPaciente4, 144);
    lv_obj_set_align(ui_LabelNotasPaciente4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNotasPaciente4, "");
    lv_obj_set_style_text_font(ui_LabelNotasPaciente4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inicio2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_inicio2, 469);
    lv_obj_set_height(ui_inicio2, 108);
    lv_obj_set_x(ui_inicio2, 0);
    lv_obj_set_y(ui_inicio2, 259);
    lv_obj_set_align(ui_inicio2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_inicio2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_inicio2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_inicio2, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_inicio2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInicio2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelInicio2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInicio2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInicio2, -7);
    lv_obj_set_y(ui_LabelInicio2, 259);
    lv_obj_set_align(ui_LabelInicio2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInicio2, "INICIO");
    lv_obj_set_style_text_font(ui_LabelInicio2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_inicio2, ui_event_inicio2, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_PanelDatos = NULL;
    ui_LabelDatos = NULL;
    ui_PanelNombre = NULL;
    ui_LabelNombre3 = NULL;
    ui_LabelNombrePaciente4 = NULL;
    ui_PanelEdad = NULL;
    ui_LabelEdad = NULL;
    ui_LabelEdadPaciente4 = NULL;
    ui_PanelIngesoFecha = NULL;
    ui_LabelFechaIngreso = NULL;
    ui_LabelIngresoFecha4 = NULL;
    ui_PanelNotas = NULL;
    ui_LabelNotas = NULL;
    ui_LabelNotasPaciente4 = NULL;
    ui_inicio2 = NULL;
    ui_LabelInicio2 = NULL;

}
