// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2-esp_now

#include "ui.h"

lv_obj_t * uic_Labelssid;
lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_PanelDatos1 = NULL;
lv_obj_t * ui_Labelssid = NULL;
lv_obj_t * ui_Labelversion = NULL;
lv_obj_t * ui_PanelNombre1 = NULL;
lv_obj_t * ui_Labelrssi = NULL;
lv_obj_t * ui_PanelEdad1 = NULL;
lv_obj_t * ui_LabelEdad1 = NULL;
lv_obj_t * ui_Labelgatenway = NULL;
lv_obj_t * ui_PanelNotas1 = NULL;
lv_obj_t * ui_LabelNotas1 = NULL;
lv_obj_t * ui_LabelRelaypeer = NULL;
lv_obj_t * ui_inicio1 = NULL;
lv_obj_t * ui_LabelInicio1 = NULL;
// event funtions
void ui_event_inicio1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelDatos1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_PanelDatos1, 469);
    lv_obj_set_height(ui_PanelDatos1, 70);
    lv_obj_set_x(ui_PanelDatos1, 0);
    lv_obj_set_y(ui_PanelDatos1, -280);
    lv_obj_set_align(ui_PanelDatos1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDatos1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelssid = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Labelssid, 300);
    lv_obj_set_height(ui_Labelssid, 42);
    lv_obj_set_x(ui_Labelssid, -64);
    lv_obj_set_y(ui_Labelssid, -280);
    lv_obj_set_align(ui_Labelssid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelssid, "Tipo De La RED");
    lv_obj_set_style_text_color(ui_Labelssid, lv_color_hex(0x46BDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelssid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelssid, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelssid, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelversion = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Labelversion, 114);
    lv_obj_set_height(ui_Labelversion, 42);
    lv_obj_set_x(ui_Labelversion, 165);
    lv_obj_set_y(ui_Labelversion, -280);
    lv_obj_set_align(ui_Labelversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelversion, "version");
    lv_obj_set_style_text_color(ui_Labelversion, lv_color_hex(0x46BDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelversion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelversion, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNombre1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_PanelNombre1, 469);
    lv_obj_set_height(ui_PanelNombre1, 70);
    lv_obj_set_x(ui_PanelNombre1, 0);
    lv_obj_set_y(ui_PanelNombre1, -172);
    lv_obj_set_align(ui_PanelNombre1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNombre1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelrssi = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Labelrssi, 455);
    lv_obj_set_height(ui_Labelrssi, 57);
    lv_obj_set_x(ui_Labelrssi, 0);
    lv_obj_set_y(ui_Labelrssi, -172);
    lv_obj_set_align(ui_Labelrssi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrssi, "");
    lv_obj_set_style_text_font(ui_Labelrssi, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEdad1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_PanelEdad1, 469);
    lv_obj_set_height(ui_PanelEdad1, 70);
    lv_obj_set_x(ui_PanelEdad1, 0);
    lv_obj_set_y(ui_PanelEdad1, -73);
    lv_obj_set_align(ui_PanelEdad1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelEdad1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelEdad1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelEdad1, 135);
    lv_obj_set_height(ui_LabelEdad1, 22);
    lv_obj_set_x(ui_LabelEdad1, -166);
    lv_obj_set_y(ui_LabelEdad1, -124);
    lv_obj_set_align(ui_LabelEdad1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEdad1, "GATEWAY:");
    lv_obj_set_style_text_color(ui_LabelEdad1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEdad1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEdad1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelgatenway = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Labelgatenway, 455);
    lv_obj_set_height(ui_Labelgatenway, 57);
    lv_obj_set_x(ui_Labelgatenway, 0);
    lv_obj_set_y(ui_Labelgatenway, -74);
    lv_obj_set_align(ui_Labelgatenway, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelgatenway, "");
    lv_obj_set_style_text_font(ui_Labelgatenway, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotas1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_PanelNotas1, 469);
    lv_obj_set_height(ui_PanelNotas1, 185);
    lv_obj_set_x(ui_PanelNotas1, 0);
    lv_obj_set_y(ui_PanelNotas1, 104);
    lv_obj_set_align(ui_PanelNotas1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNotas1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNotas1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelNotas1, 192);
    lv_obj_set_height(ui_LabelNotas1, 28);
    lv_obj_set_x(ui_LabelNotas1, -129);
    lv_obj_set_y(ui_LabelNotas1, -13);
    lv_obj_set_align(ui_LabelNotas1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNotas1, "RELAY PEER");
    lv_obj_set_style_text_color(ui_LabelNotas1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNotas1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNotas1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelaypeer = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelRelaypeer, 469);
    lv_obj_set_height(ui_LabelRelaypeer, 185);
    lv_obj_set_x(ui_LabelRelaypeer, 0);
    lv_obj_set_y(ui_LabelRelaypeer, 104);
    lv_obj_set_align(ui_LabelRelaypeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRelaypeer, "");
    lv_obj_set_style_text_font(ui_LabelRelaypeer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inicio1 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_inicio1, 469);
    lv_obj_set_height(ui_inicio1, 108);
    lv_obj_set_x(ui_inicio1, 0);
    lv_obj_set_y(ui_inicio1, 259);
    lv_obj_set_align(ui_inicio1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_inicio1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_inicio1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_inicio1, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_inicio1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInicio1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelInicio1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInicio1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInicio1, -7);
    lv_obj_set_y(ui_LabelInicio1, 259);
    lv_obj_set_align(ui_LabelInicio1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInicio1, "INICIO");
    lv_obj_set_style_text_font(ui_LabelInicio1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_inicio1, ui_event_inicio1, LV_EVENT_ALL, NULL);
    uic_Labelssid = ui_Labelssid;

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_PanelDatos1 = NULL;
    uic_Labelssid = NULL;
    ui_Labelssid = NULL;
    ui_Labelversion = NULL;
    ui_PanelNombre1 = NULL;
    ui_Labelrssi = NULL;
    ui_PanelEdad1 = NULL;
    ui_LabelEdad1 = NULL;
    ui_Labelgatenway = NULL;
    ui_PanelNotas1 = NULL;
    ui_LabelNotas1 = NULL;
    ui_LabelRelaypeer = NULL;
    ui_inicio1 = NULL;
    ui_LabelInicio1 = NULL;

}
