// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_calls(lv_event_t * e);
extern lv_obj_t * ui_calls;
extern lv_obj_t * ui_nuse;
extern void ui_event_PanelS(lv_event_t * e);
extern lv_obj_t * ui_PanelS;
extern lv_obj_t * ui_LabelHora;
extern lv_obj_t * ui_LabelAMPM;
extern void ui_event_InfoPaciente(lv_event_t * e);
extern lv_obj_t * ui_InfoPaciente;
extern void ui_event_InfoPaciente2(lv_event_t * e);
extern lv_obj_t * ui_InfoPaciente2;
extern void ui_event_namepaciente(lv_event_t * e);
extern lv_obj_t * ui_namepaciente;
extern lv_obj_t * ui_LabelNombre;
extern void ui_event_ubi1(lv_event_t * e);
extern lv_obj_t * ui_ubi1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_call;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

