// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"

lv_obj_t * ui_Screen0 = NULL;
lv_obj_t * ui_RESET3 = NULL;
lv_obj_t * ui_RESET4 = NULL;
// event funtions
void ui_event_RESET3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RESET3 = lv_btn_create(ui_Screen0);
    lv_obj_set_width(ui_RESET3, 469);
    lv_obj_set_height(ui_RESET3, 108);
    lv_obj_set_x(ui_RESET3, 0);
    lv_obj_set_y(ui_RESET3, 259);
    lv_obj_set_align(ui_RESET3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RESET3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RESET3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RESET3, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RESET3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RESET4 = lv_label_create(ui_Screen0);
    lv_obj_set_width(ui_RESET4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RESET4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RESET4, 1);
    lv_obj_set_y(ui_RESET4, 260);
    lv_obj_set_align(ui_RESET4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RESET4, "RESET");
    lv_obj_set_style_text_font(ui_RESET4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RESET3, ui_event_RESET3, LV_EVENT_ALL, NULL);

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_del(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    ui_RESET3 = NULL;
    ui_RESET4 = NULL;

}
