// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREENWELCOME_H
#define UI_SCREENWELCOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screenwelcome
extern void ui_Screenwelcome_screen_init(void);
extern void ui_Screenwelcome_screen_destroy(void);
extern lv_obj_t * ui_Screenwelcome;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

