// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2-esp_now

#ifndef _ESP32_S3_TOUCH_LCD_2_8_V2_ESP_NOW_UI_H
#define _ESP32_S3_TOUCH_LCD_2_8_V2_ESP_NOW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen0.h"
#include "ui_Screen4.h"
#include "ui_Screenwelcome.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_nursev3_png);    // assets/nursev3.png
LV_IMG_DECLARE(ui_img_ubi_png);    // assets/ubi.png
LV_IMG_DECLARE(ui_img_led_green_png);    // assets/led_green.png
LV_IMG_DECLARE(ui_img_colgar_png);    // assets/colgar.png
LV_IMG_DECLARE(ui_img_led_red_png);    // assets/led_red.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
