// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2-esp_now

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_PanelDatos2 = NULL;
lv_obj_t * ui_Labelconfig = NULL;
lv_obj_t * ui_PanelNombre2 = NULL;
lv_obj_t * ui_Labelmsdebug = NULL;
lv_obj_t * ui_inicio3 = NULL;
lv_obj_t * ui_LabelInicio3 = NULL;
lv_obj_t * ui_Switchtms = NULL;
lv_obj_t * ui_Panelmsdebug = NULL;
lv_obj_t * ui_Labelmonitorserial = NULL;
lv_obj_t * ui_Sliderbrillo = NULL;
lv_obj_t * ui_Labelmsdebug1 = NULL;
// event funtions
void ui_event_inicio3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelDatos2 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_PanelDatos2, 469);
    lv_obj_set_height(ui_PanelDatos2, 70);
    lv_obj_set_x(ui_PanelDatos2, 0);
    lv_obj_set_y(ui_PanelDatos2, -280);
    lv_obj_set_align(ui_PanelDatos2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDatos2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelconfig = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Labelconfig, 463);
    lv_obj_set_height(ui_Labelconfig, 42);
    lv_obj_set_x(ui_Labelconfig, 0);
    lv_obj_set_y(ui_Labelconfig, -278);
    lv_obj_set_align(ui_Labelconfig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelconfig, "Configuracion");
    lv_obj_set_style_text_color(ui_Labelconfig, lv_color_hex(0x46BDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelconfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Labelconfig, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelconfig, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNombre2 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_PanelNombre2, 469);
    lv_obj_set_height(ui_PanelNombre2, 70);
    lv_obj_set_x(ui_PanelNombre2, 0);
    lv_obj_set_y(ui_PanelNombre2, -172);
    lv_obj_set_align(ui_PanelNombre2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNombre2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelmsdebug = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Labelmsdebug, 145);
    lv_obj_set_height(ui_Labelmsdebug, 25);
    lv_obj_set_x(ui_Labelmsdebug, 152);
    lv_obj_set_y(ui_Labelmsdebug, -225);
    lv_obj_set_align(ui_Labelmsdebug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmsdebug, "MS_DEBUG");
    lv_obj_set_style_text_color(ui_Labelmsdebug, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelmsdebug, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelmsdebug, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inicio3 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_inicio3, 469);
    lv_obj_set_height(ui_inicio3, 108);
    lv_obj_set_x(ui_inicio3, 0);
    lv_obj_set_y(ui_inicio3, 259);
    lv_obj_set_align(ui_inicio3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_inicio3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_inicio3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_inicio3, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_inicio3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInicio3 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelInicio3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInicio3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInicio3, -7);
    lv_obj_set_y(ui_LabelInicio3, 259);
    lv_obj_set_align(ui_LabelInicio3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInicio3, "INICIO");
    lv_obj_set_style_text_font(ui_LabelInicio3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switchtms = lv_switch_create(ui_Screen6);
    lv_obj_set_width(ui_Switchtms, 81);
    lv_obj_set_height(ui_Switchtms, 35);
    lv_obj_set_x(ui_Switchtms, 181);
    lv_obj_set_y(ui_Switchtms, -172);
    lv_obj_set_align(ui_Switchtms, LV_ALIGN_CENTER);

    ui_Panelmsdebug = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panelmsdebug, 469);
    lv_obj_set_height(ui_Panelmsdebug, 324);
    lv_obj_set_x(ui_Panelmsdebug, 0);
    lv_obj_set_y(ui_Panelmsdebug, 35);
    lv_obj_set_align(ui_Panelmsdebug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panelmsdebug, LV_OBJ_FLAG_SCROLLABLE);        /// scroll habilitado
    lv_obj_set_scroll_dir(ui_Panelmsdebug, LV_DIR_VER);              /// solo scroll vertical
    lv_obj_set_style_pad_all(ui_Panelmsdebug, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmonitorserial = lv_label_create(ui_Panelmsdebug);        /// hijo del panel
    lv_obj_set_width(ui_Labelmonitorserial, 461);
    lv_obj_set_height(ui_Labelmonitorserial, LV_SIZE_CONTENT);       /// crece con el contenido
    lv_obj_set_x(ui_Labelmonitorserial, 0);
    lv_obj_set_y(ui_Labelmonitorserial, 0);
    lv_obj_set_align(ui_Labelmonitorserial, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Labelmonitorserial, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_Labelmonitorserial, "Monitor de pantalla, para visualizar active el MS_DEBUG");
    lv_obj_set_style_text_font(ui_Labelmonitorserial, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Sliderbrillo = lv_slider_create(ui_Screen6);
    lv_slider_set_value(ui_Sliderbrillo, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderbrillo) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderbrillo, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderbrillo, 305);
    lv_obj_set_height(ui_Sliderbrillo, 30);
    lv_obj_set_x(ui_Sliderbrillo, -48);
    lv_obj_set_y(ui_Sliderbrillo, -171);
    lv_obj_set_align(ui_Sliderbrillo, LV_ALIGN_CENTER);

    ui_Labelmsdebug1 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Labelmsdebug1, 145);
    lv_obj_set_height(ui_Labelmsdebug1, 25);
    lv_obj_set_x(ui_Labelmsdebug1, -73);
    lv_obj_set_y(ui_Labelmsdebug1, -225);
    lv_obj_set_align(ui_Labelmsdebug1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmsdebug1, "SCR_BRT");
    lv_obj_set_style_text_color(ui_Labelmsdebug1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelmsdebug1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelmsdebug1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_inicio3, ui_event_inicio3, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_PanelDatos2 = NULL;
    ui_Labelconfig = NULL;
    ui_PanelNombre2 = NULL;
    ui_Labelmsdebug = NULL;
    ui_inicio3 = NULL;
    ui_LabelInicio3 = NULL;
    ui_Switchtms = NULL;
    ui_Panelmsdebug = NULL;
    ui_Labelmonitorserial = NULL;
    ui_Sliderbrillo = NULL;
    ui_Labelmsdebug1 = NULL;

}
