// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_calls1;
extern void ui_event_PanelS1(lv_event_t * e);
extern lv_obj_t * ui_PanelS1;
extern lv_obj_t * ui_cronometro;
extern lv_obj_t * ui_LabelCons1;
extern lv_obj_t * ui_PanelI1;
extern lv_obj_t * ui_PanelI4;
extern lv_obj_t * ui_LabelNombre1;
extern void ui_event_finishs(lv_event_t * e);
extern lv_obj_t * ui_finishs;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_ubi2;
extern lv_obj_t * ui_ledgreen;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_namepaciente1;
extern lv_obj_t * ui_ledred;
// CUSTOM VARIABLES
extern lv_obj_t * uic_calls1;
extern lv_obj_t * uic_finish;
extern lv_obj_t * uic_led_green;
extern lv_obj_t * uic_led_red;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

