// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"
#include "iot_config.h"

// ========================================
// Welcome Screen - Animación de Carga CLINUM
// ========================================
lv_obj_t * ui_Screenwelcome = NULL;

// Colores CLINUM (médico/salud - azul turquesa y verde)
#define CLINUM_PRIMARY   0x00BCD4    // Cyan médico
#define CLINUM_SECONDARY 0x4CAF50    // Verde salud #03a0d5
#define CLINUM_ACCENT    0x2196F3    // Azul tecnología
#define CLINUM_BG        0x000000    // Fondo oscuro profesional #000000
#define CLINUM_ICON_COLOR 0x6CA2F3   // Color para icono 'i' y ondas #6ca2f3

// Callback para animación de opacidad (ondas apareciendo/desapareciendo)
static void wave_opacity_cb(void * var, int32_t v)
{
    lv_obj_set_style_border_opa((lv_obj_t*)var, v, 0);
}

// Callback para fade de texto
static void text_fade_cb(void * var, int32_t v)
{
    lv_obj_set_style_opa((lv_obj_t*)var, v, 0);
}

// Callback para barra de progreso
static void progress_cb(void * var, int32_t v)
{
    lv_bar_set_value((lv_obj_t*)var, v, LV_ANIM_OFF);
}

void ui_Screenwelcome_screen_init(void)
{
    // ========================================
    // Crear pantalla de bienvenida
    // ========================================
    ui_Screenwelcome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenwelcome, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screenwelcome, lv_color_hex(CLINUM_BG), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screenwelcome, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ========================================
    // Texto "CL  NUM" (sin la "i" - será la animada)
    // ========================================
    lv_obj_t * text_left = lv_label_create(ui_Screenwelcome);
    lv_label_set_text(text_left, "CL  NUM");
    lv_obj_set_style_text_color(text_left, lv_color_hex(CLINUM_PRIMARY), 0);
    lv_obj_set_style_text_font(text_left, &lv_font_montserrat_48, 0);
    lv_obj_align(text_left, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_opa(text_left, LV_OPA_TRANSP, 0);
    
    

    // ========================================
    // ONDAS tipo WiFi encima del punto (3 arcos) - estilo logo CLINUM
    // Arcos más redondeados y más anchos para mayor curvatura
    // ========================================
    
    // Onda 1 - Más alejada (más ancha, curva y redondeada)
    lv_obj_t * wave1 = lv_obj_create(ui_Screenwelcome);      // Crear objeto contenedor para la onda
    lv_obj_set_size(wave1, 100, 60);                         // Tamaño: 100px ancho x 60px alto (rectángulo horizontal)
    lv_obj_align(wave1, LV_ALIGN_CENTER, -28, -58);          // Posición: centrado, -10px horizontal, -58px vertical
    lv_obj_set_style_bg_opa(wave1, LV_OPA_TRANSP, 0);        // Fondo transparente (solo mostrar borde)
    lv_obj_set_style_border_width(wave1, 5, 0);              // Grosor del borde: 5px (más grueso = más visible)
    lv_obj_set_style_border_color(wave1, lv_color_hex(CLINUM_ICON_COLOR), 0); // Color del borde: azul verdoso CLINUM
    lv_obj_set_style_border_opa(wave1, 255, 0);              // Opacidad inicial: VISIBLE para prueba
    lv_obj_set_style_radius(wave1, 60, 0);                   // Radio: 60px (más redondeado - casi semicírculo)
    lv_obj_set_style_border_side(wave1, LV_BORDER_SIDE_TOP, 0); // Solo borde superior (arco)
    
    // Onda 2 - Media (más redondeada)
    lv_obj_t * wave2 = lv_obj_create(ui_Screenwelcome);      // Crear objeto para onda media
    lv_obj_set_size(wave2, 76, 46);                          // Tamaño: 76px ancho x 46px alto (más pequeña)
    lv_obj_align(wave2, LV_ALIGN_CENTER, -28, -54);          // Posición: más cerca del centro (-54px vertical)
    lv_obj_set_style_bg_opa(wave2, LV_OPA_TRANSP, 0);        // Fondo transparente
    lv_obj_set_style_border_width(wave2, 5, 0);              // Grosor del borde: 5px
    lv_obj_set_style_border_color(wave2, lv_color_hex(CLINUM_ICON_COLOR), 0); // Color: azul verdoso CLINUM
    lv_obj_set_style_border_opa(wave2, 255, 0);              // Opacidad inicial: VISIBLE para prueba
    lv_obj_set_style_radius(wave2, 46, 0);                   // Radio: 46px (más redondeado)
    lv_obj_set_style_border_side(wave2, LV_BORDER_SIDE_TOP, 0); // Solo borde superior
    
    // Onda 3 - Más cercana (más redondeada)
    lv_obj_t * wave3 = lv_obj_create(ui_Screenwelcome);      // Crear objeto para onda interna
    lv_obj_set_size(wave3, 52, 32);                          // Tamaño: 52px ancho x 32px alto (la más pequeña)
    lv_obj_align(wave3, LV_ALIGN_CENTER, -28, -50);          // Posición: más cerca del punto (-50px vertical)
    lv_obj_set_style_bg_opa(wave3, LV_OPA_TRANSP, 0);        // Fondo transparente
    lv_obj_set_style_border_width(wave3, 5, 0);              // Grosor del borde: 5px
    lv_obj_set_style_border_color(wave3, lv_color_hex(CLINUM_ICON_COLOR), 0); // Color: azul verdoso CLINUM
    lv_obj_set_style_border_opa(wave3, 255, 0);              // Opacidad inicial: VISIBLE para prueba
    lv_obj_set_style_radius(wave3, 32, 0);                   // Radio: 32px (más redondeado)
    lv_obj_set_style_border_side(wave3, LV_BORDER_SIDE_TOP, 0); // Solo borde superior


    // ========================================
    // PUNTO de la "i" (círculo)
    // ========================================
    lv_obj_t * i_dot = lv_obj_create(ui_Screenwelcome);      // Crear objeto para el punto
    lv_obj_set_size(i_dot, 14, 14);                          // Tamaño: 14x14px (cuadrado -> círculo con radius)
    lv_obj_align(i_dot, LV_ALIGN_CENTER, -28, -36);          // Posición: debajo de las ondas (-28px vertical)
    lv_obj_set_style_radius(i_dot, LV_RADIUS_CIRCLE, 0);     // Radio: círculo perfecto
    lv_obj_set_style_bg_color(i_dot, lv_color_hex(CLINUM_ICON_COLOR), 0); // Color de fondo: azul verdoso CLINUM
    lv_obj_set_style_bg_opa(i_dot, LV_OPA_COVER, 0);         // Opacidad: completamente opaco (visible)
    lv_obj_set_style_border_width(i_dot, 0, 0);              // Sin borde
    
    // ========================================
    // BARRA VERTICAL de la "i"
    // ========================================
    lv_obj_t * i_stem = lv_obj_create(ui_Screenwelcome);     // Crear objeto para el palo vertical
    lv_obj_set_size(i_stem, 12, 40);                         // Tamaño: 12px ancho x 40px alto (rectángulo corto)
    lv_obj_align(i_stem, LV_ALIGN_CENTER, -28, 0);           // Posición: debajo del punto (8px vertical)
    lv_obj_set_style_bg_color(i_stem, lv_color_hex(CLINUM_ICON_COLOR), 0); // Color de fondo: azul verdoso CLINUM
    lv_obj_set_style_bg_opa(i_stem, LV_OPA_COVER, 0);        // Opacidad: completamente opaco
    lv_obj_set_style_border_width(i_stem, 1, 1);             // Sin borde
    lv_obj_set_style_radius(i_stem, 0, 0);                   // Radio: 0 (esquinas cuadradas)

    // ========================================
    // Barra de progreso
    // ========================================
    lv_obj_t * progress_bar = lv_bar_create(ui_Screenwelcome); // Crear barra de progreso
    lv_obj_set_size(progress_bar, 240, 6);                   // Tamaño: 200px ancho x 6px alto (barra delgada)
    lv_obj_align(progress_bar, LV_ALIGN_CENTER, 0, 30);     // Posición: abajo (5px desde el centro)
    lv_obj_set_style_bg_color(progress_bar, lv_color_hex(0x2C3E50), LV_PART_MAIN); // Color fondo: gris oscuro
    lv_obj_set_style_bg_opa(progress_bar, LV_OPA_COVER, LV_PART_MAIN); // Opacidad fondo: opaco
    lv_obj_set_style_bg_color(progress_bar, lv_color_hex(CLINUM_SECONDARY), LV_PART_INDICATOR); // Color indicador: verde
    lv_obj_set_style_bg_opa(progress_bar, LV_OPA_COVER, LV_PART_INDICATOR); // Opacidad indicador: opaco
    lv_obj_set_style_radius(progress_bar, 3, LV_PART_MAIN);  // Radio esquinas: 3px (bordes redondeados)
    lv_bar_set_value(progress_bar, 0, LV_ANIM_OFF);          // Valor inicial: 0% (sin animación)

    // ========================================
    // ANIMACIONES
    // ========================================
    
    // Animación onda 1 - Aparece y desaparece (ciclo: 0->200->0)
    static lv_anim_t wave1_anim;                             // Variable de animación (debe ser static)
    lv_anim_init(&wave1_anim);                               // Inicializar estructura de animación
    lv_anim_set_var(&wave1_anim, wave1);                     // Asignar objeto a animar (wave1)
    lv_anim_set_exec_cb(&wave1_anim, wave_opacity_cb);       // Callback: función que cambia la opacidad
    lv_anim_set_values(&wave1_anim, 0, 200);                 // Valores: de 0 (transparente) a 200 (casi opaco)
    lv_anim_set_time(&wave1_anim, 1000);                     // Duración: 1000ms (1 segundo) para aparecer
    lv_anim_set_playback_time(&wave1_anim, 1000);            // Tiempo reversa: 1000ms para desaparecer
    lv_anim_set_repeat_count(&wave1_anim, LV_ANIM_REPEAT_INFINITE); // Repetir: infinitamente
    lv_anim_set_path_cb(&wave1_anim, lv_anim_path_ease_in_out);     // Curva: suave entrada/salida
    lv_anim_start(&wave1_anim);                              // Iniciar animación
    
    // Animación onda 2 - Desfasada 300ms (efecto secuencial)
    static lv_anim_t wave2_anim;                             // Variable de animación
    lv_anim_init(&wave2_anim);                               // Inicializar
    lv_anim_set_var(&wave2_anim, wave2);                     // Objeto a animar: wave2
    lv_anim_set_exec_cb(&wave2_anim, wave_opacity_cb);       // Callback de opacidad
    lv_anim_set_values(&wave2_anim, 0, 220);                 // Valores: 0 a 220 (un poco más opaca que wave1)
    lv_anim_set_time(&wave2_anim, 1000);                     // Duración: 1 segundo
    lv_anim_set_delay(&wave2_anim, 300);                     // Delay: 300ms (empieza después de wave1)
    lv_anim_set_playback_time(&wave2_anim, 1000);            // Tiempo reversa: 1 segundo
    lv_anim_set_repeat_count(&wave2_anim, LV_ANIM_REPEAT_INFINITE); // Repetir infinitamente
    lv_anim_set_path_cb(&wave2_anim, lv_anim_path_ease_in_out);     // Curva suave
    lv_anim_start(&wave2_anim);                              // Iniciar
    
    // Animación onda 3 - Desfasada 600ms (la más retrasada)
    static lv_anim_t wave3_anim;                             // Variable de animación
    lv_anim_init(&wave3_anim);                               // Inicializar
    lv_anim_set_var(&wave3_anim, wave3);                     // Objeto a animar: wave3
    lv_anim_set_exec_cb(&wave3_anim, wave_opacity_cb);       // Callback de opacidad
    lv_anim_set_values(&wave3_anim, 0, 255);                 // Valores: 0 a 255 (totalmente opaca)
    lv_anim_set_time(&wave3_anim, 1000);                     // Duración: 1 segundo
    lv_anim_set_delay(&wave3_anim, 600);                     // Delay: 600ms (empieza al último)
    lv_anim_set_playback_time(&wave3_anim, 1000);            // Tiempo reversa: 1 segundo
    lv_anim_set_repeat_count(&wave3_anim, LV_ANIM_REPEAT_INFINITE); // Repetir infinitamente
    lv_anim_set_path_cb(&wave3_anim, lv_anim_path_ease_in_out);     // Curva suave
    lv_anim_start(&wave3_anim);                              // Iniciar
    
    // Animación texto izquierdo "CL  NUM" - Fade in
    static lv_anim_t text_left_anim;                         // Variable de animación
    lv_anim_init(&text_left_anim);                           // Inicializar
    lv_anim_set_var(&text_left_anim, text_left);             // Objeto a animar: text_left
    lv_anim_set_exec_cb(&text_left_anim, text_fade_cb);      // Callback: cambia opacidad del texto
    lv_anim_set_values(&text_left_anim, 0, 255);             // Valores: 0 (invisible) a 255 (visible)
    lv_anim_set_time(&text_left_anim, 800);                  // Duración: 800ms (fade suave)
    lv_anim_set_delay(&text_left_anim, 400);                 // Delay: 400ms antes de empezar
    lv_anim_set_path_cb(&text_left_anim, lv_anim_path_ease_out); // Curva: desaceleración al final
    lv_anim_start(&text_left_anim);                          // Iniciar (solo una vez)
    
    // Animación barra de progreso - Llenado 0% a 100%
    static lv_anim_t progress_anim;                          // Variable de animación
    lv_anim_init(&progress_anim);                            // Inicializar
    lv_anim_set_var(&progress_anim, progress_bar);           // Objeto a animar: progress_bar
    lv_anim_set_exec_cb(&progress_anim, progress_cb);        // Callback: actualiza valor de la barra
    lv_anim_set_values(&progress_anim, 0, 100);              // Valores: de 0% a 100%
    lv_anim_set_time(&progress_anim, WELCOME_DURATION_MS);   // Completar al terminar la pantalla de bienvenida
    lv_anim_set_path_cb(&progress_anim, lv_anim_path_ease_out); // Curva: desaceleración (más lento al final)
    lv_anim_start(&progress_anim);                           // Iniciar
}

void ui_Screenwelcome_screen_destroy(void)
{
    if(ui_Screenwelcome) lv_obj_del(ui_Screenwelcome);
    ui_Screenwelcome = NULL;
}