// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"

lv_obj_t * uic_led_red;
lv_obj_t * uic_led_green;
lv_obj_t * uic_finish;
lv_obj_t * uic_calls1;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_calls1 = NULL;
lv_obj_t * ui_PanelS1 = NULL;
lv_obj_t * ui_cronometro = NULL;
lv_obj_t * ui_LabelCons1 = NULL;
lv_obj_t * ui_PanelI1 = NULL;
lv_obj_t * ui_PanelI4 = NULL;
lv_obj_t * ui_LabelNombre1 = NULL;
lv_obj_t * ui_finishs = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ubi2 = NULL;
lv_obj_t * ui_ledgreen = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_namepaciente1 = NULL;
lv_obj_t * ui_ledred = NULL;
// event funtions
void ui_event_PanelS1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_finishs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 250, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calls1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_calls1, 300);
    lv_obj_set_height(ui_calls1, 150);
    lv_obj_set_x(ui_calls1, 0);
    lv_obj_set_y(ui_calls1, -137);
    lv_obj_set_align(ui_calls1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calls1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_calls1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_calls1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_calls1, lv_color_hex(0x074E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calls1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_calls1, lv_color_hex(0xC11010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_calls1, lv_color_hex(0xC7DCC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_calls1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_calls1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelS1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelS1, 469);
    lv_obj_set_height(ui_PanelS1, 70);
    lv_obj_set_x(ui_PanelS1, 0);
    lv_obj_set_y(ui_PanelS1, -280);
    lv_obj_set_align(ui_PanelS1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cronometro = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_cronometro, 218);
    lv_obj_set_height(ui_cronometro, 48);
    lv_obj_set_x(ui_cronometro, -114);
    lv_obj_set_y(ui_cronometro, -282);
    lv_obj_set_align(ui_cronometro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cronometro, "00:00:00");
    lv_obj_set_style_text_color(ui_cronometro, lv_color_hex(0x6AF9BA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cronometro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cronometro, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCons1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelCons1, 56);
    lv_obj_set_height(ui_LabelCons1, 45);
    lv_obj_set_x(ui_LabelCons1, 196);
    lv_obj_set_y(ui_LabelCons1, -280);
    lv_obj_set_align(ui_LabelCons1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCons1, "00");
    lv_obj_set_style_text_color(ui_LabelCons1, lv_color_hex(0x6AF9BA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCons1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCons1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelI1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelI1, 469);
    lv_obj_set_height(ui_PanelI1, 70);
    lv_obj_set_x(ui_PanelI1, 0);
    lv_obj_set_y(ui_PanelI1, 280);
    lv_obj_set_align(ui_PanelI1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelI1, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelI1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelI4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelI4, 469);
    lv_obj_set_height(ui_PanelI4, 70);
    lv_obj_set_x(ui_PanelI4, 0);
    lv_obj_set_y(ui_PanelI4, 204);
    lv_obj_set_align(ui_PanelI4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelI4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelI4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelI4, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelI4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombre1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelNombre1, 402);
    lv_obj_set_height(ui_LabelNombre1, 30);
    lv_obj_set_x(ui_LabelNombre1, 28);
    lv_obj_set_y(ui_LabelNombre1, 280);
    lv_obj_set_align(ui_LabelNombre1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombre1, "LabelNombre");
    lv_obj_set_style_text_font(ui_LabelNombre1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_finishs = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_finishs, 300);
    lv_obj_set_height(ui_finishs, 150);
    lv_obj_set_x(ui_finishs, 0);
    lv_obj_set_y(ui_finishs, 41);
    lv_obj_set_align(ui_finishs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_finishs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_finishs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_finishs, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_finishs, lv_color_hex(0x074E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_finishs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_finishs, lv_color_hex(0xC11010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_finishs, lv_color_hex(0xC7DCC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_finishs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_finishs, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 61);
    lv_obj_set_y(ui_Label12, -136);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, " INSISTIR\nLLAMADO");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 59);
    lv_obj_set_y(ui_Label13, 37);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "FINALIZAR\nLLAMADO");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ubi2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_ubi2, &ui_img_ubi_png);
    lv_obj_set_width(ui_ubi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ubi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ubi2, -206);
    lv_obj_set_y(ui_ubi2, 280);
    lv_obj_set_align(ui_ubi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ubi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ubi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ubi2, 180);

    ui_ledgreen = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_ledgreen, &ui_img_led_green_png);
    lv_obj_set_width(ui_ledgreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledgreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledgreen, -69);
    lv_obj_set_y(ui_ledgreen, -139);
    lv_obj_set_align(ui_ledgreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ledgreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ledgreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ledgreen, 260);

    ui_Image17 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image17, &ui_img_colgar_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, -75);
    lv_obj_set_y(ui_Image17, 38);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image17, 250);

    ui_namepaciente1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_namepaciente1, 454);
    lv_obj_set_height(ui_namepaciente1, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_namepaciente1, 0);
    lv_obj_set_y(ui_namepaciente1, 201);
    lv_obj_set_align(ui_namepaciente1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namepaciente1, "");
    lv_obj_set_style_text_align(ui_namepaciente1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namepaciente1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledred = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_ledred, &ui_img_led_red_png);
    lv_obj_set_width(ui_ledred, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledred, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledred, -68);
    lv_obj_set_y(ui_ledred, -134);
    lv_obj_set_align(ui_ledred, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ledred, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ledred, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ledred, 250);

    lv_obj_add_event_cb(ui_PanelS1, ui_event_PanelS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_finishs, ui_event_finishs, LV_EVENT_ALL, NULL);
    uic_calls1 = ui_calls1;
    uic_finish = ui_finishs;
    uic_led_green = ui_ledgreen;
    uic_led_red = ui_ledred;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    uic_calls1 = NULL;
    ui_calls1 = NULL;
    ui_PanelS1 = NULL;
    ui_cronometro = NULL;
    ui_LabelCons1 = NULL;
    ui_PanelI1 = NULL;
    ui_PanelI4 = NULL;
    ui_LabelNombre1 = NULL;
    uic_finish = NULL;
    ui_finishs = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_ubi2 = NULL;
    uic_led_green = NULL;
    ui_ledgreen = NULL;
    ui_Image17 = NULL;
    ui_namepaciente1 = NULL;
    uic_led_red = NULL;
    ui_ledred = NULL;

}
