// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2

#include "ui.h"

lv_obj_t * uic_inicio;
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_PanelS2 = NULL;
lv_obj_t * ui_PanelI2 = NULL;
lv_obj_t * ui_LabelHora2 = NULL;
lv_obj_t * ui_LabelAMPM2 = NULL;
lv_obj_t * ui_LabelNombre2 = NULL;
lv_obj_t * ui_ubi3 = NULL;
lv_obj_t * ui_TabView1Info = NULL;
lv_obj_t * ui_Labelubicacionsede = NULL;
lv_obj_t * ui_PanelIp = NULL;
lv_obj_t * ui_PanelMac = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_inicio = NULL;
lv_obj_t * ui_LabelIp = NULL;
lv_obj_t * ui_LabelMac = NULL;
lv_obj_t * ui_LabelInicio = NULL;
lv_obj_t * ui_RESET = NULL;
lv_obj_t * ui_RESET1 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_EspNowConfigButton = NULL;
lv_obj_t * ui_EspNowConfigPanel = NULL;
lv_obj_t * ui_EspNowMacInput = NULL;
lv_obj_t * ui_EspNowChannelDropdown = NULL;
lv_obj_t * ui_EspNowConfigStatus = NULL;
lv_obj_t * ui_EspNowKeyboard = NULL;

static const char * espnow_mac_keyboard_map[] = {
    "1", "2", "3", "A", "\n",
    "4", "5", "6", "B", "\n",
    "7", "8", "9", "C", "\n",
    "0", "D", "E", "F", "\n",
    ":", LV_SYMBOL_BACKSPACE, LV_SYMBOL_CLOSE, LV_SYMBOL_OK, ""
};

static const lv_btnmatrix_ctrl_t espnow_mac_keyboard_ctrl[] = {
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 1, 1, 1,
    1, 2, 2, 2
};
// event funtions
void ui_event_PanelIp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_inicio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_RESET(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
    }
}

static void ui_event_EspNowConfigButton(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        extern void prepareEspNowConfigUi(void);
        prepareEspNowConfigUi();
    }
}

static void ui_event_EspNowMacInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED || event_code == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(ui_EspNowKeyboard, ui_EspNowMacInput);
        lv_obj_clear_flag(ui_EspNowKeyboard, LV_OBJ_FLAG_HIDDEN);
    }
}

static void ui_event_EspNowKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_READY || event_code == LV_EVENT_CANCEL) {
        lv_obj_add_flag(ui_EspNowKeyboard, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_state(ui_EspNowMacInput, LV_STATE_FOCUSED);
    }
}

static void ui_event_EspNowSave(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        extern void saveEspNowConfigFromUi(const char *gatewayMac, uint8_t channel);
        saveEspNowConfigFromUi(lv_textarea_get_text(ui_EspNowMacInput),
                               (uint8_t)(lv_dropdown_get_selected(ui_EspNowChannelDropdown) + 1));
    }
}

static void ui_event_EspNowCancel(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) ui_hide_espnow_config();
}

void ui_show_espnow_config(const char *gatewayMac, uint8_t channel)
{
    if(ui_EspNowMacInput && gatewayMac) lv_textarea_set_text(ui_EspNowMacInput, gatewayMac);
    if(ui_EspNowChannelDropdown && channel >= 1 && channel <= 13)
        lv_dropdown_set_selected(ui_EspNowChannelDropdown, channel - 1);
    if(ui_EspNowConfigStatus) lv_label_set_text(ui_EspNowConfigStatus, "Edite los datos y pulse GUARDAR");
    if(ui_EspNowKeyboard) lv_obj_add_flag(ui_EspNowKeyboard, LV_OBJ_FLAG_HIDDEN);
    if(ui_EspNowConfigPanel) lv_obj_clear_flag(ui_EspNowConfigPanel, LV_OBJ_FLAG_HIDDEN);
}

void ui_hide_espnow_config(void)
{
    if(ui_EspNowKeyboard) lv_obj_add_flag(ui_EspNowKeyboard, LV_OBJ_FLAG_HIDDEN);
    if(ui_EspNowConfigPanel) lv_obj_add_flag(ui_EspNowConfigPanel, LV_OBJ_FLAG_HIDDEN);
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelS2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelS2, 469);
    lv_obj_set_height(ui_PanelS2, 70);
    lv_obj_set_x(ui_PanelS2, 0);
    lv_obj_set_y(ui_PanelS2, -280);
    lv_obj_set_align(ui_PanelS2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelI2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelI2, 469);
    lv_obj_set_height(ui_PanelI2, 70);
    lv_obj_set_x(ui_PanelI2, 0);
    lv_obj_set_y(ui_PanelI2, 280);
    lv_obj_set_align(ui_PanelI2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelI2, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelI2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHora2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelHora2, 140);
    lv_obj_set_height(ui_LabelHora2, 31);
    lv_obj_set_x(ui_LabelHora2, -156);
    lv_obj_set_y(ui_LabelHora2, -285);
    lv_obj_set_align(ui_LabelHora2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHora2, "00:00:00");
    lv_obj_set_style_text_font(ui_LabelHora2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAMPM2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelAMPM2, 56);
    lv_obj_set_height(ui_LabelAMPM2, 30);
    lv_obj_set_x(ui_LabelAMPM2, -64);
    lv_obj_set_y(ui_LabelAMPM2, -285);
    lv_obj_set_align(ui_LabelAMPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAMPM2, "A/P");
    lv_obj_set_style_text_font(ui_LabelAMPM2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNombre2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelNombre2, 402);
    lv_obj_set_height(ui_LabelNombre2, 30);
    lv_obj_set_x(ui_LabelNombre2, 28);
    lv_obj_set_y(ui_LabelNombre2, 280);
    lv_obj_set_align(ui_LabelNombre2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNombre2, "LabelNombre");
    lv_obj_set_style_text_font(ui_LabelNombre2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ubi3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ubi3, &ui_img_ubi_png);
    lv_obj_set_width(ui_ubi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ubi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ubi3, -206);
    lv_obj_set_y(ui_ubi3, 280);
    lv_obj_set_align(ui_ubi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ubi3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ubi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ubi3, 180);

    ui_TabView1Info = lv_tabview_create(ui_Screen3, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1Info, 469);
    lv_obj_set_height(ui_TabView1Info, 475);
    lv_obj_set_x(ui_TabView1Info, -1);
    lv_obj_set_y(ui_TabView1Info, 0);
    lv_obj_set_align(ui_TabView1Info, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1Info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelubicacionsede = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Labelubicacionsede, 454);
    lv_obj_set_height(ui_Labelubicacionsede, 41);
    lv_obj_set_x(ui_Labelubicacionsede, 0);
    lv_obj_set_y(ui_Labelubicacionsede, -212);
    lv_obj_set_align(ui_Labelubicacionsede, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelubicacionsede, "Infomacion Device");
    lv_obj_set_style_text_align(ui_Labelubicacionsede, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelubicacionsede, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIp = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelIp, 469);
    lv_obj_set_height(ui_PanelIp, 70);
    lv_obj_set_x(ui_PanelIp, 0);
    lv_obj_set_y(ui_PanelIp, -146);
    lv_obj_set_align(ui_PanelIp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMac = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelMac, 469);
    lv_obj_set_height(ui_PanelMac, 70);
    lv_obj_set_x(ui_PanelMac, 0);
    lv_obj_set_y(ui_PanelMac, -71);
    lv_obj_set_align(ui_PanelMac, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 469);
    lv_obj_set_height(ui_Panel2, 70);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 4);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_inicio = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_inicio, 150);
    lv_obj_set_height(ui_inicio, 100);
    lv_obj_set_x(ui_inicio, -137);
    lv_obj_set_y(ui_inicio, 178);
    lv_obj_set_align(ui_inicio, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_inicio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_inicio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_inicio, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_inicio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIp = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelIp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIp, -12);
    lv_obj_set_y(ui_LabelIp, -149);
    lv_obj_set_align(ui_LabelIp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIp, "000.000.000.000");
    lv_obj_set_style_text_font(ui_LabelIp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMac = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelMac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMac, -8);
    lv_obj_set_y(ui_LabelMac, -73);
    lv_obj_set_align(ui_LabelMac, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMac, "00:00:00:00:00:00");
    lv_obj_set_style_text_font(ui_LabelMac, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInicio = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelInicio, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInicio, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInicio, -136);
    lv_obj_set_y(ui_LabelInicio, 177);
    lv_obj_set_align(ui_LabelInicio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInicio, "INICIO");
    lv_obj_set_style_text_font(ui_LabelInicio, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RESET = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_RESET, 150);
    lv_obj_set_height(ui_RESET, 100);
    lv_obj_set_x(ui_RESET, 137);
    lv_obj_set_y(ui_RESET, 178);
    lv_obj_set_align(ui_RESET, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RESET, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RESET, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RESET, lv_color_hex(0x433D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RESET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RESET1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_RESET1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RESET1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RESET1, 136);
    lv_obj_set_y(ui_RESET1, 177);
    lv_obj_set_align(ui_RESET1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RESET1, "RESET");
    lv_obj_set_style_text_font(ui_RESET1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_Label32, -15);
    lv_obj_set_y(ui_Label32, -283);
    lv_obj_set_align(ui_Label32, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label32, "CLINUM-2.0");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x46BDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 4);
    lv_obj_set_y(ui_Label33, 3);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "ESP32-S3 WAVE-TFT2\"");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 469);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 79);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -7);
    lv_obj_set_y(ui_Label34, 81);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Dinamica y Desarrollo");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelIp, ui_event_PanelIp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inicio, ui_event_inicio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RESET, ui_event_RESET, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);

    ui_EspNowConfigButton = lv_btn_create(ui_Screen3);
    lv_obj_set_size(ui_EspNowConfigButton, 110, 100);
    lv_obj_set_x(ui_EspNowConfigButton, 0);
    lv_obj_set_y(ui_EspNowConfigButton, 178);
    lv_obj_set_align(ui_EspNowConfigButton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_EspNowConfigButton, lv_color_hex(0x215A75), 0);
    lv_obj_t * configButtonLabel = lv_label_create(ui_EspNowConfigButton);
    lv_label_set_text(configButtonLabel, "CONFIG");
    lv_obj_set_style_text_font(configButtonLabel, &lv_font_montserrat_18, 0);
    lv_obj_center(configButtonLabel);
    lv_obj_add_event_cb(ui_EspNowConfigButton, ui_event_EspNowConfigButton, LV_EVENT_ALL, NULL);

    ui_EspNowConfigPanel = lv_obj_create(lv_layer_top());
    lv_obj_set_size(ui_EspNowConfigPanel, 469, 500);
    lv_obj_align(ui_EspNowConfigPanel, LV_ALIGN_CENTER, 0, -20);
    lv_obj_set_style_bg_color(ui_EspNowConfigPanel, lv_color_hex(0x20252B), 0);
    lv_obj_set_style_bg_opa(ui_EspNowConfigPanel, LV_OPA_COVER, 0);
    lv_obj_clear_flag(ui_EspNowConfigPanel, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t * configTitle = lv_label_create(ui_EspNowConfigPanel);
    lv_label_set_text(configTitle, "CONFIGURACION ESP-NOW");
    lv_obj_set_style_text_font(configTitle, &lv_font_montserrat_24, 0);
    lv_obj_align(configTitle, LV_ALIGN_TOP_MID, 0, 4);

    lv_obj_t * channelLabel = lv_label_create(ui_EspNowConfigPanel);
    lv_label_set_text(channelLabel, "Canal");
    lv_obj_set_style_text_font(channelLabel, &lv_font_montserrat_20, 0);
    lv_obj_align(channelLabel, LV_ALIGN_TOP_LEFT, 8, 55);

    ui_EspNowChannelDropdown = lv_dropdown_create(ui_EspNowConfigPanel);
    lv_dropdown_set_options(ui_EspNowChannelDropdown, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13");
    lv_obj_set_size(ui_EspNowChannelDropdown, 250, 50);
    lv_obj_align(ui_EspNowChannelDropdown, LV_ALIGN_TOP_RIGHT, -8, 45);
    lv_obj_set_style_text_font(ui_EspNowChannelDropdown, &lv_font_montserrat_20, 0);

    lv_obj_t * macLabel = lv_label_create(ui_EspNowConfigPanel);
    lv_label_set_text(macLabel, "MAC gateway");
    lv_obj_set_style_text_font(macLabel, &lv_font_montserrat_20, 0);
    lv_obj_align(macLabel, LV_ALIGN_TOP_LEFT, 8, 120);

    ui_EspNowMacInput = lv_textarea_create(ui_EspNowConfigPanel);
    lv_textarea_set_one_line(ui_EspNowMacInput, true);
    lv_textarea_set_max_length(ui_EspNowMacInput, 17);
    lv_textarea_set_accepted_chars(ui_EspNowMacInput, "0123456789ABCDEF:");
    lv_textarea_set_placeholder_text(ui_EspNowMacInput, "AA:BB:CC:DD:EE:FF");
    lv_obj_set_size(ui_EspNowMacInput, 425, 52);
    lv_obj_align(ui_EspNowMacInput, LV_ALIGN_TOP_MID, 0, 150);
    lv_obj_set_style_text_font(ui_EspNowMacInput, &lv_font_montserrat_20, 0);
    lv_obj_add_event_cb(ui_EspNowMacInput, ui_event_EspNowMacInput, LV_EVENT_ALL, NULL);

    ui_EspNowConfigStatus = lv_label_create(ui_EspNowConfigPanel);
    lv_obj_set_width(ui_EspNowConfigStatus, 425);
    lv_label_set_text(ui_EspNowConfigStatus, "Edite los datos y pulse GUARDAR");
    lv_obj_set_style_text_align(ui_EspNowConfigStatus, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_EspNowConfigStatus, &lv_font_montserrat_16, 0);
    lv_obj_align(ui_EspNowConfigStatus, LV_ALIGN_TOP_MID, 0, 215);

    lv_obj_t * cancelButton = lv_btn_create(ui_EspNowConfigPanel);
    lv_obj_set_size(cancelButton, 170, 60);
    lv_obj_align(cancelButton, LV_ALIGN_TOP_LEFT, 20, 255);
    lv_obj_t * cancelLabel = lv_label_create(cancelButton);
    lv_label_set_text(cancelLabel, "CANCELAR");
    lv_obj_center(cancelLabel);
    lv_obj_add_event_cb(cancelButton, ui_event_EspNowCancel, LV_EVENT_ALL, NULL);

    lv_obj_t * saveButton = lv_btn_create(ui_EspNowConfigPanel);
    lv_obj_set_size(saveButton, 170, 60);
    lv_obj_align(saveButton, LV_ALIGN_TOP_RIGHT, -20, 255);
    lv_obj_set_style_bg_color(saveButton, lv_color_hex(0x238A4B), 0);
    lv_obj_t * saveLabel = lv_label_create(saveButton);
    lv_label_set_text(saveLabel, "GUARDAR");
    lv_obj_center(saveLabel);
    lv_obj_add_event_cb(saveButton, ui_event_EspNowSave, LV_EVENT_ALL, NULL);

    ui_EspNowKeyboard = lv_keyboard_create(ui_EspNowConfigPanel);
    lv_keyboard_set_map(ui_EspNowKeyboard, LV_KEYBOARD_MODE_USER_1,
                        espnow_mac_keyboard_map, espnow_mac_keyboard_ctrl);
    lv_keyboard_set_mode(ui_EspNowKeyboard, LV_KEYBOARD_MODE_USER_1);
    lv_keyboard_set_textarea(ui_EspNowKeyboard, ui_EspNowMacInput);
    lv_obj_set_size(ui_EspNowKeyboard, 445, 260);
    lv_obj_align(ui_EspNowKeyboard, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_event_cb(ui_EspNowKeyboard, ui_event_EspNowKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_flag(ui_EspNowKeyboard, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_EspNowConfigPanel, LV_OBJ_FLAG_HIDDEN);
    uic_inicio = ui_inicio;

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_EspNowConfigPanel) lv_obj_del(ui_EspNowConfigPanel);
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_PanelS2 = NULL;
    ui_PanelI2 = NULL;
    ui_LabelHora2 = NULL;
    ui_LabelAMPM2 = NULL;
    ui_LabelNombre2 = NULL;
    ui_ubi3 = NULL;
    ui_TabView1Info = NULL;
    ui_Labelubicacionsede = NULL;
    ui_PanelIp = NULL;
    ui_PanelMac = NULL;
    ui_Panel2 = NULL;
    uic_inicio = NULL;
    ui_inicio = NULL;
    ui_LabelIp = NULL;
    ui_LabelMac = NULL;
    ui_LabelInicio = NULL;
    ui_RESET = NULL;
    ui_RESET1 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;
    ui_Panel1 = NULL;
    ui_Label34 = NULL;
    ui_EspNowConfigButton = NULL;
    ui_EspNowConfigPanel = NULL;
    ui_EspNowMacInput = NULL;
    ui_EspNowChannelDropdown = NULL;
    ui_EspNowConfigStatus = NULL;
    ui_EspNowKeyboard = NULL;

}
