// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-LCD-2.8-V2-esp_now

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_PanelDatos1;
extern lv_obj_t * ui_Labelssid;
extern lv_obj_t * ui_Labelversion;
extern lv_obj_t * ui_PanelNombre1;
extern lv_obj_t * ui_Labelrssi;
extern lv_obj_t * ui_PanelEdad1;
extern lv_obj_t * ui_LabelEdad1;
extern lv_obj_t * ui_Labelgatenway;
extern lv_obj_t * ui_PanelNotas1;
extern lv_obj_t * ui_LabelNotas1;
extern lv_obj_t * ui_LabelRelaypeer;
extern void ui_event_inicio1(lv_event_t * e);
extern lv_obj_t * ui_inicio1;
extern lv_obj_t * ui_LabelInicio1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Labelssid;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

